using System;
using System.Collections.Generic;
using System.Linq;

namespace RageLightEditor.Editor
{
    public static class ParticleEffectNames_V71
    {
        public static readonly string[] Ambient =
        {
            "AMB_ABATTOIR_ACID_BATH",
            "AMB_ABATTOIR_CARCASS_DRIP",
            "AMB_ABATTOIR_SAW_BLOOD",
            "AMB_BARREL_FIRE",
            "AMB_BEACH_CAMPFIRE",
            "AMB_BUBBLE_STREAM",
            "AMB_BUTTERFLYS",
            "AMB_CANDLE_FLAME",
            "AMB_CIG_SMOKE_LINGER",
            "AMB_CH2_FARM_FIRE_DBLE",
            "AMB_CH2_FARM_FIRE_U_L",
            "AMB_CH2_FARM_FIRE_U_S",
            "AMB_CH2_FARM_FIRE_L_L_L",
            "AMB_CH2_FARM_RESI_DBLE",
            "AMB_CH2_FARM_SMOKE_DBLE",
            "AMB_CLUCK_BATH_STEAM",
            "AMB_COLD_AIR_FLOOR",
            "AMB_COLD_AIR_VENT",
            "AMB_COCKROACHES",
            "AMB_DRAIN_WATER",
            "AMB_DRY_ICE_AREA",
            "AMB_DRY_ICE_VENT",
            "AMB_DUST_DEVIL_RURAL_LRG",
            "AMB_DUST_DEVIL_RURAL_SMA",
            "AMB_DUST_DEVIL_URBAN_LRG",
            "AMB_DUST_DEVIL_URBAN_SMA",
            "AMB_DUST_MOTES",
            "AMB_ELECTRIC_CRACKLE",
            "AMB_FALLING_LEAVES_L",
            "AMB_FALLING_LEAVES_M",
            "AMB_FALLING_LEAVES_PALM",
            "AMB_FALLING_LEAVES_PINE",
            "AMB_FALLING_LEAVES_FICUS",
            "AMB_FALLING_LEAVES_OAK",
            "AMB_FALLING_CHERRY_BLOSSOM",
            "AMB_FALLING_LEAVES_S",
            "AMB_FBI_FIRE_DRIP",
            "AMB_FBI_FIRE_FOGBALL",
            "AMB_FBI_SMOKE_FOGBALL",
            "AMB_FBI_SMOKE_LINGER_LT",
            "AMB_FBI_SMOKE_LINGER_HVY",
            "AMB_FBI_SMOKE_LAND_LT",
            "AMB_FBI_SMOKE_LAND_MED",
            "AMB_FBI_SMOKE_LAND_HVY",
            "AMB_FBI_STAIR_SMOKE_GATHER",
            "AMB_FBI_SMOKE_RAMP_LT",
            "AMB_FBI_SMOKE_RAMP_MED",
            "AMB_FBI_SMOKE_RAMP_HVY",
            "AMB_FBI_SMOKE_DOOR_LT",
            "AMB_FBI_SMOKE_DOOR_MED",
            "AMB_FBI_SMOKE_DOOR_HVY",
            "AMB_FBI_SMOKE_EDGE_LIP",
            "AMB_FBI_ELEC_CRACKLE",
            "AMB_FBI_FIRE_SMALL",
            "AMB_FBI_FIRE_LARGE",
            "AMB_FBI_FIRE_WALL_LARGE",
            "AMB_FBI_FIRE_WALL_SMALL",
            "AMB_FBI_FIRE_BEAM",
            "AMB_FBI_FIRE_DOOR",
            "AMB_FBI_FIRE_DOUBLEDOOR",
            "AMB_FBI_CINDER",
            "AMB_FBI_SMOULDER_LARGE_3A",
            "AMB_FBI_SMOULDER_SMALL_3A",
            "AMB_FBI_SMOULDER_LARGE_3B",
            "AMB_FBI_SMOULDER_SMALL_3B",
            "AMB_FBI_SMOKE_CREEP",
            "AMB_FBI_FALLING_DEBRIS",
            "AMB_FBI_FIRE_SMOKE",
            "AMB_FBI_SMALL_FLAMES",
            "AMB_FBI_SPARK_LIVE_WIRES",
            "AMB_FBI_GROUND_DEBRIS",
            "AMB_FBI_FALLING_DUST",
            "AMB_FIRE_GASWORKS",
            "AMB_FIRE_RING",
            "AMB_FLY_SWARM",
            "AMB_FLY_ZAPPED",
            "AMB_FOUNDRY_ARC_FURNACE",
            "AMB_OWENSHEPARD_FOGBALL",
            "AMB_FOUNDRY_FOGBALL",
            "AMB_FOUNDRY_DUST",
            "AMB_FOUNDRY_MOLTEN_POUR",
            "AMB_FOUNDRY_MOLTEN_STEAM",
            "AMB_FOUNDRY_MOLTEN_HAZE",
            "AMB_FOUNTAIN_DOUBLE",
            "AMB_FOUNTAIN_MANSION2",
            "AMB_FOUNTAIN_ARCADIUS",
            "AMB_FOUNTAIN_RODEO",
            "AMB_FOUNTAIN_POUR",
            "AMB_GENERATOR_SMOKE",
            "AMB_INSECT_SWARM",
            "AMB_INSECT_PLANE",
            "AMB_INT_FIREPLACE",
            "AMB_INT_WATERFALL_RUNOFF",
            "AMB_INT_WATERFALL_SPLASH",
            "AMB_JACUZZI",
            "AMB_JOSH3_SMALL_HOUSE_FIRES",
            "AMB_JOSH3_HOUSE_SMOKED",
            "AMB_MACHINE_EXHAUST_THICK",
            "AMB_MACHINE_EXHAUST_THIN",
            "AMB_MOTHS",
            "AMB_MOTHS_CUPBOARD",
            "AMB_MOTHS_NIGHTTIME",
            "AMB_PAL_HELI_EXPLOSION",
            "AMB_PAL_HELI_SILT",
            "AMB_PAL_HELI_S_FIRE",
            "AMB_PAL_HELI_SPARK_WIRES",
            "AMB_PAL_HELI_WATER",
            "AMB_RAY_FAM3_DUST_MOTES",
            "AMB_RAY_FINALE1_FIRE",
            "AMB_RAY_FINALE1_PETROL",
            "AMB_RAY_FBI5A_LIGHT_DOOR",
            "AMB_RAY_PALETO_GAS_PLUME",
            "AMB_RAY_PALETO_GAS_PLUME_L",
            "AMB_RAY_PALETO_GAS_FLAMES",
            "AMB_RAY_PROLOGUE_ELEC_CRACKLE",
            "AMB_RAY_SHIPWRECK_BUBBLES",
            "AMB_RAY_SHIPWRECK_OIL",
            "AMB_RAY_SHIPWRECK_FIRE",
            "AMB_RAY_FINALE_VAULT_HAZE",
            "AMB_RAY_FINALE_VAULT_SPARKS",
            "AMB_PALETO_GAS_WINDOW_FIRE",
            "AMB_PEEING",
            "AMB_PRO_BDOOR_WATER_DRIP",
            "AMB_PROLOGUE_ELECTRICALS",
            "AMB_PROLOGUE_SPRINKLER_ON",
            "AMB_PROLOGUE_SPRINKLER_OFF",
            "AMB_RIVER_MIST_GEN",
            "AMB_RIVER_SPLASH_GEN",
            "AMB_RIVER_FLOATING_DEBRIS",
            "AMB_SEWER_DRIPS_LG",
            "AMB_SEWER_DRIPS_MED",
            "AMB_SEWER_DRIPS_SM",
            "AMB_SMOKE_CHICKEN",
            "AMB_SMOKE_FACTORY",
            "AMB_SMOKE_FOUNDRY",
            "AMB_SMOKE_FACTORY_WHITE",
            "AMB_SMOKE_FOUNDRY_WHITE",
            "AMB_SMOKE_GASWORKS",
            "AMB_SMOKE_GEN_FACTORY",
            "AMB_SMOKE_SCRAPYARD",
            "AMB_STEAM_DIRECTED",
            "AMB_SNOW_MIST_BASE",
            "AMB_SNOW_MIST_UPPER",
            "AMB_SOL1_PLANE_WRECK",
            "AMB_SPARKING_WIRES",
            "AMB_SPARKING_WIRES_SMALL",
            "AMB_SPRINKLER_CITY_1AM-5AM",
            "AMB_SPRINKLER_CITY_2PM-4PM",
            "AMB_SPRINKLER_CITY_7AM-11AM",
            "AMB_SPRINKLER_CROP",
            "AMB_SPRINKLER_GOLF",
            "AMB_STEAM_PIPE_HVY",
            "AMB_SPRINKLER_INT_ON",
            "AMB_SPRINKLER_INT_OFF",
            "AMB_STEAM_PIPE_LGT",
            "AMB_STEAM_VENT_PRISON",
            "AMB_STEAM_VENT_OPEN_HVY",
            "AMB_STEAM_VENT_OPEN_LGT",
            "AMB_STEAM_VENT_ROUND",
            "AMB_STEAM_VENT_RND_HVY",
            "AMB_STONER_DUST_DROP",
            "AMB_STONER_FALLING_DEBRIS",
            "AMB_STONER_RUBBLE_DROP",
            "AMB_STONER_VENT_SMOKE",
            "AMB_TNL_BUBBLES_LGE",
            "AMB_TNL_BUBBLES_SML",
            "AMB_TORCH_FIRE",
            "AMB_TORCH_FIRE_NIGHT",
            "AMB_TRAIN_WATER_WASH",
            "AMB_TREV1_METH_FIRES",
            "AMB_TREV1_TRAILER_SPLASH_F",
            "AMB_TREV1_TRAILER_SPLASH_S",
            "AMB_TAP_DRIP",
            "AMB_TROPICAL_FISH_YELLOW",
            "AMB_TROPICAL_FISH_GOLD",
            "AMB_TROPICAL_FISH_BLUE",
            "AMB_TROPICAL_FISH_STRIP",
            "AMB_VENT_HAZE_LG",
            "AMB_VENT_HAZE_SM",
            "AMB_WATER_DRIPS_LG",
            "AMB_WATER_DRIPS_MED",
            "AMB_WATER_DRIPS_SM",
            "AMB_WATERFALL_TOP",
            "AMB_WATERFALL_PNT_SPLASH",
            "AMB_WATERFALL_BASE",
            "AMB_WATERFALL_POOL",
            "AMB_WATER_ROOF_DRIPS",
            "AMB_WATER_ROOF_DRIPS_SHORT",
            "AMB_WATER_ROOF_POUR_SHORT",
            "AMB_WATER_ROOF_POUR_LONG",
            "AMB_WIND_DUST",
            "AMB_WIND_DUST_DIRECTED",
            "AMB_WIND_DUST_SWIRL",
            "AMB_WIND_HAY",
            "AMB_WIND_HAY_DIRECTED",
            "AMB_WIND_GRASS",
            "AMB_WIND_GRASS_DIRECTED",
            "AMB_WIND_LEAVES",
            "AMB_WIND_LEAVES_DIRECTED",
            "AMB_WIND_LEAVES_SWIRL",
            "AMB_WIND_LEAVES_TREE_TOP",
            "AMB_WIND_LITTER",
            "AMB_WIND_LITTER_DIRECTED",
            "AMB_WIND_LITTER_SWIRL",
            "AMB_WIND_LITTER_RANDOM",
            "AMB_WIND_SAND_DUNE",
            "AMB_WATERFALL_SPLASH_SML",
            "AMB_WATERFALL_SPLASH_MED",
            "AMB_WATERFALL_SPLASH_LRG",
            "AMB_RAPID_AREA_SPRAY",
            "AMB_RAPID_DIR_SPRAY",
            "AMB_RAPID_DIR_SPLASH",
            "AMB_RAPID_DIR_SPLASH_WIDE",
            "AMB_RAPID_AREA_SPRAY_HVY",
            "AMB_RAPID_ROCK_DRIPS",
            "AMB_RAPID_DIR_SPLASH_LIGHT",
            "AMB_STONER_WOODCHIP_DROP",
            "AMB_STONER_WOODCHIP_FALLING",
            "AMB_PAL_HELI_SQ_FIRE",
            "AMB_PAL_HELI_L_FIRE",
            "AMB_PAL_HELI_H_FIRE",
            "AMB_PAL_HELI_EMBERS",
            "AMB_INT_FIREPLACE_SML",
            "AMB_WATER_DRIPS_DAM",
            "AMB_WATER_SPLASHES",
        };

        public static IEnumerable<string> Find(string text, int limit = 60)
        {
            if (string.IsNullOrWhiteSpace(text)) return Ambient.Take(limit);
            var t = text.Trim();
            return Ambient.Where(n => n.IndexOf(t, StringComparison.OrdinalIgnoreCase) >= 0).Take(limit);
        }

        public static int SelfTest_V71(Action<string, bool, string> check)
        {
            int fails = 0;
            void Chk(string what, bool ok, string d) { if (!ok) fails++; check(what, ok, d); }
            Chk("v71 effects: the ambient effect list is loaded",
                Ambient.Length >= 190, Ambient.Length + " names");
            Chk("v71 effects: no name is in there twice",
                Ambient.Distinct(StringComparer.OrdinalIgnoreCase).Count() == Ambient.Length,
                Ambient.Length + " unique");
            var fire = Find("fire").ToList();
            Chk("v71 effects: searching finds them by any part of the name",
                fire.Count > 5 && fire.All(n => n.IndexOf("fire", StringComparison.OrdinalIgnoreCase) >= 0),
                fire.Count + " match fire, first " + fire.FirstOrDefault());
            Chk("v71 effects: ...including the ones the report listed",
                Ambient.Contains("AMB_TORCH_FIRE") && Ambient.Contains("AMB_WATER_SPLASHES") &&
                Ambient.Contains("AMB_ABATTOIR_ACID_BATH"),
                "first and last are present");
            return fails;
        }
    }
}
